### ISSUE TITLE
Holodeck ceiling lighting effect get teleported when ending the hololab program

### ISSUE THREAD

**Issue by GuuscoNL** [oninoni/startrekmodules#12]
When you end the holodeck program hololab the light effects from the ceiling lights get teleported to where the "inner" area is.
**Screenshot:**
![image](https://user-images.githubusercontent.com/99217547/187051789-2af5beaf-d7e8-44c0-9015-a103b7132859.png)

I tried to debug it myself, but this is above my pay grade. (No idea why this is happening😅)

**Comment by oninoni** [comment]
Fixed https://github.com/oninoni/startrekmodules/commit/3203586a183c45701a14c865769f4337f227cf47
